name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build nodejs
        run: |
          npm run build
      - name: build docker image
        run: |
          docker build . -t giordanotin/jjodel:latest
      - name: push image to docker hub
        run: |
          docker login -u giordanotin -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push giordanotin/jjodel:latest
